name: Build-Marble
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Kernel Source
        run: |
          git clone --depth=1 https://github.com/LowTension/android_kernel_xiaomi_sm8475 kernel
          echo "--- СПИСОК ВСЕХ КОНФИГОВ ---"
          find kernel/arch/arm64/configs -name "*defconfig"
